import os
import uuid
from typing import List, Dict, Any
from dotenv import load_dotenv

load_dotenv()

from sentence_transformers import SentenceTransformer
from graph.state import AgentState, SynthesisResult, CritiqueResult, Chunk
from retrieval.qdrant_store import qdrant_store


class WriterAgent:
    """Formats synthesis into structured Markdown report. Stores to Qdrant memory."""
    
    def __init__(self):
        self.embedder = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")
    
    def run(self, state: AgentState) -> str:
        if state.declined:
            return self._format_decline(state)
        return self._format_report(state)
    
    @staticmethod
    def _confidence_bar(score: float, width: int = 10) -> str:
        """Render a confidence score as a filled/empty block bar, e.g. '▓▓▓▓▓▓▓▓░░ 0.82'."""
        filled = max(0, min(width, round(score * width)))
        bar = "▓" * filled + "░" * (width - filled)
        return f"`{bar}` {score:.2f}"

    def _format_report(self, state: AgentState) -> str:
        synthesis = state.synthesis
        critique = state.critique
        
        # Build citation map FIRST — needed by findings
        citation_map = self._build_citation_map(state)
        
        # Safe quality score formatting
        quality_str = f"{critique.quality_score:.2f}" if critique else "N/A"
        threshold_str = f"{state.plan.quality_threshold:.2f}" if state.plan else "N/A"
        
        lines = [
            f"# {state.research_question}",
            "",
            f"*Generated by InSyfy | Quality score: {quality_str} | Sources: {len(state.search_results)}*",
            "",
            "## Executive Summary",
            ""
        ]
        
        # Executive summary from top 2-3 findings
        if synthesis and synthesis.key_findings:
            top_findings = sorted(
                synthesis.key_findings,
                key=lambda f: f.confidence,
                reverse=True
            )[:3]
            summary = "; ".join([f.claim for f in top_findings])
            lines.append(summary[:500])
        else:
            lines.append("No findings available.")
        
        lines.extend(["", "## Key Findings", ""])
        
        if synthesis:
            for i, finding in enumerate(synthesis.key_findings, 1):
                # Build deduped footnote numbers from supporting chunks —
                # several chunks often share one source, so we collapse
                # them to unique citation numbers instead of listing every
                # chunk (and instead of repeating full titles per finding).
                seen_nums = set()
                footnotes = []
                for chunk_id in (finding.supporting_chunks or []):
                    info = citation_map.get(chunk_id)
                    if info and info["num"] not in seen_nums:
                        seen_nums.add(info["num"])
                        footnotes.append(info["num"])
                footnotes.sort()

                lines.append(f"### Finding {i}: {finding.claim}")
                conf_str = (
                    self._confidence_bar(finding.confidence)
                    if finding.confidence is not None else "N/A"
                )
                lines.append(f"- Confidence: {conf_str}")
                if footnotes:
                    refs = " ".join(f"[{n}]" for n in footnotes)
                    lines.append(f"- Sources: {refs}")
                if finding.contradictions:
                    lines.append(f"- ⚠️ Contradictions: {'; '.join(finding.contradictions)}")
                lines.append("")
        
        # Limitations
        lines.extend(["## Evidence Gaps & Limitations", ""])
        if critique and critique.gap_analysis:
            lines.append(critique.gap_analysis)
        if state.quality_warning:
            lines.append("\n**Warning:** Quality threshold not met after maximum retries.")
        lines.append("")
        
        # Sources (numbered footnotes for reference)
        lines.extend(["## Sources", ""])
        unique_citations = {info["num"]: info for info in citation_map.values()}
        for num in sorted(unique_citations):
            info = unique_citations[num]
            lines.append(f"[{info['num']}] {info['title']} — {info['url']}")
        
        # Methodology
        total_chunks = sum(len(r.chunks) for r in state.search_results) + len(state.rag_chunks)
        lines.extend([
            "",
            "## Methodology",
            f"- Sub-queries searched: {len(state.plan.sub_queries) if state.plan else 0}",
            f"- Total chunks retrieved: {total_chunks}",
            f"- Retrieval methods: web search + Qdrant hybrid (vector + keyword + cross-encoder rerank)",
            f"- Quality score: {quality_str} (threshold: {threshold_str})",
            f"- Retry iterations: {state.retry_count}"
        ])
        
        report = "\n".join(lines)
        
        # Store to Qdrant memory
        self._store_to_memory(state, report)
        
        return report
    
    def _format_decline(self, state: AgentState) -> str:
        chunks_count = sum(len(r.chunks) for r in state.search_results) + len(state.rag_chunks)
        
        return f"""## Insufficient Evidence

InSyfy retrieved {chunks_count} chunks for this query, but none met the minimum evidence threshold.

**Question:** {state.research_question}

**Reason:** {state.decline_reason}

This means the system cannot produce a reliable, grounded answer.

**What to try:**
- Rephrase the question with more specific terms
- Expand the search depth setting
- Try a different topic with more available sources
"""
    
    def _build_citation_map(self, state: AgentState) -> Dict[str, Dict[str, Any]]:
        """Map chunk IDs to citation numbers.

        Citations are deduped by source_url, not chunk_id: several chunks
        commonly come from the same page, and each one should point at the
        same footnote rather than minting a new numbered source every time.
        """
        citations: Dict[str, Dict[str, Any]] = {}   # chunk_id -> citation info
        url_to_citation: Dict[str, Dict[str, Any]] = {}  # source_url -> citation info
        counter = 1

        def _register(chunk):
            nonlocal counter
            url = chunk.metadata.source_url
            title = chunk.metadata.source_title or "Source"

            if url not in url_to_citation:
                url_to_citation[url] = {
                    "num": counter,
                    "title": title,
                    "url": url
                }
                counter += 1

            citations[chunk.chunk_id] = url_to_citation[url]

        for result in state.search_results:
            for chunk in result.chunks:
                _register(chunk)

        for chunk in state.rag_chunks:
            _register(chunk)

        return citations
    
    def _store_to_memory(self, state: AgentState, report: str):
        """Store chunks and report summary to Qdrant."""
        try:
            # Store all chunks
            all_chunks = []
            for result in state.search_results:
                all_chunks.extend(result.chunks)
            all_chunks.extend(state.rag_chunks)
            
            if all_chunks:
                texts = [c.text for c in all_chunks]
                embeddings = self.embedder.encode(texts).tolist()
                qdrant_store.store_chunks(all_chunks, embeddings, state.run_id)
            
            # Store report executive summary
            summary = ""
            if "## Executive Summary" in report:
                try:
                    summary = report.split("## Executive Summary")[1].split("##")[0].strip()
                except:
                    summary = report[:500]
            else:
                summary = report[:500]
            
            summary_embedding = self.embedder.encode([summary]).tolist()[0]
            
            from qdrant_client.models import PointStruct
            report_point_id = str(uuid.uuid5(uuid.NAMESPACE_DNS, f"report_{state.run_id}"))
            qdrant_store.client.upsert(
                collection_name=qdrant_store.collection_name,
                points=[PointStruct(
                    id=report_point_id,
                    vector=summary_embedding,
                    payload={
                        "text": summary,
                        "question": state.research_question,
                        "run_id": state.run_id,
                        "quality_score": state.critique.quality_score if state.critique else 0.0,
                        "type": "report_summary"
                    }
                )]
            )
            
        except Exception as e:
            print(f"Memory storage warning: {e}")