import os
import uuid
from typing import List, Dict, Any
from dotenv import load_dotenv

load_dotenv()

from sentence_transformers import SentenceTransformer
from graph.state import AgentState, SynthesisResult, CritiqueResult, Chunk
from retrieval.qdrant_store import qdrant_store


class WriterAgent:
    """Formats synthesis into structured Markdown report. Stores to Qdrant memory."""
    
    def __init__(self):
        self.embedder = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")
        # Populated by _format_report(); read by graph/nodes.py after run()
        # so state.citations and the report's own Sources section always
        # agree — one citation map, one place it's built.
        self.last_citations: List[Dict[str, Any]] = []
    
    def run(self, state: AgentState) -> str:
        if state.declined:
            return self._format_decline(state)
        return self._format_report(state)
    
    @staticmethod
    def _confidence_bar(score: float, width: int = 10) -> str:
        """Render a confidence score as a filled/empty block bar, e.g. '▓▓▓▓▓▓▓▓░░ 0.82'."""
        filled = max(0, min(width, round(score * width)))
        bar = "▓" * filled + "░" * (width - filled)
        return f"`{bar}` {score:.2f}"

    @staticmethod
    def _trim_to_boundary(text: str, limit: int = 500) -> str:
        """Trim text to `limit` chars without cutting mid-word/mid-sentence.

        Prefers cutting at the last sentence end (. ! ?) within the limit;
        falls back to the last space; falls back to a hard cut only if the
        text has no natural break at all (e.g. one long unbroken token).
        """
        if len(text) <= limit:
            return text

        window = text[:limit]

        last_sentence_end = max(window.rfind(". "), window.rfind("! "), window.rfind("? "))
        if last_sentence_end > limit * 0.4:  # don't trim to a tiny fragment
            return window[:last_sentence_end + 1]

        last_space = window.rfind(" ")
        if last_space > limit * 0.4:
            return window[:last_space].rstrip(",;: ") + "…"

        return window.rstrip() + "…"

    def _format_report(self, state: AgentState) -> str:
        synthesis = state.synthesis
        critique = state.critique
        
        # Build citation map FIRST — needed by findings
        citation_map = self._build_citation_map(state)
        
        # Safe quality score formatting
        quality_str = f"{critique.quality_score:.2f}" if critique else "N/A"
        threshold_str = f"{state.plan.quality_threshold:.2f}" if state.plan else "N/A"
        unique_source_count = len({info["num"] for info in citation_map.values()})
        
        lines = [
            f"# {state.research_question}",
            "",
            f"*Generated by InSyfy | Quality score: {quality_str} | Sources: {unique_source_count}*",
            "",
            "## Executive Summary",
            ""
        ]
        
        # Executive summary: prefer the LLM-authored summary. Fall back to
        # concatenating top findings only if executive_summary is missing
        # (e.g. a cached SynthesisResult from before this field existed).
        if synthesis and synthesis.executive_summary:
            lines.append(self._trim_to_boundary(synthesis.executive_summary, 1500))
        elif synthesis and synthesis.key_findings:
            top_findings = sorted(
                synthesis.key_findings,
                key=lambda f: f.confidence,
                reverse=True
            )[:3]
            summary = "; ".join([f.claim for f in top_findings])
            lines.append(self._trim_to_boundary(summary, 1500))
        else:
            lines.append("No findings available.")
        
        lines.extend(["", "## Answers by Sub-Query", ""])
        
        if state.plan and state.plan.sub_queries and synthesis:
            findings = synthesis.key_findings or []
            for sq in state.plan.sub_queries:
                matched = self._findings_for_sub_query(sq.query, findings)
                
                lines.append(f"### {sq.query}")
                lines.append(f"*{sq.intent}*")
                lines.append("")
                
                if matched:
                    for finding in matched:
                        seen_nums = set()
                        footnotes = []
                        for chunk_id in (finding.supporting_chunks or []):
                            info = citation_map.get(chunk_id)
                            if info and info["num"] not in seen_nums:
                                seen_nums.add(info["num"])
                                footnotes.append(info["num"])
                        footnotes.sort()
                        refs = " ".join(f"[[{n}]](#src-{n})" for n in footnotes) if footnotes else ""
                        conf_str = self._confidence_bar(finding.confidence) if finding.confidence is not None else "N/A"
                        lines.append(f"- {finding.claim} ({conf_str}) {refs}".rstrip())
                else:
                    lines.append("- *Not directly addressed by current findings — see Evidence Gaps below.*")
                lines.append("")
        elif not state.plan or not state.plan.sub_queries:
            lines.append("No sub-queries were recorded for this run.")
        else:
            lines.append("No synthesis was available to map against sub-queries.")
        
        lines.extend(["", "## Key Findings", ""])
        
        if synthesis:
            for i, finding in enumerate(synthesis.key_findings, 1):
                # Build deduped footnote numbers from supporting chunks —
                # several chunks often share one source, so we collapse
                # them to unique citation numbers instead of listing every
                # chunk (and instead of repeating full titles per finding).
                seen_nums = set()
                footnotes = []
                for chunk_id in (finding.supporting_chunks or []):
                    info = citation_map.get(chunk_id)
                    if info and info["num"] not in seen_nums:
                        seen_nums.add(info["num"])
                        footnotes.append(info["num"])
                footnotes.sort()

                lines.append(f"### Finding {i}: {finding.claim}")
                conf_str = (
                    self._confidence_bar(finding.confidence)
                    if finding.confidence is not None else "N/A"
                )
                lines.append(f"- Confidence: {conf_str}")
                if footnotes:
                    refs = " ".join(f"[[{n}]](#src-{n})" for n in footnotes)
                    lines.append(f"- Sources: {refs}")
                if finding.contradictions:
                    lines.append(f"- ⚠️ Contradictions: {'; '.join(finding.contradictions)}")
                lines.append("")
        
        # Limitations
        lines.extend(["## Evidence Gaps & Limitations", ""])
        if critique and critique.gap_analysis:
            lines.append(critique.gap_analysis)
        if state.quality_warning:
            lines.append("\n**Warning:** Quality threshold not met after maximum retries.")
        lines.append("")
        
        # Sources (numbered footnotes, clickable, linked from findings above)
        lines.extend(["## Sources", ""])
        unique_citations = {info["num"]: info for info in citation_map.values()}
        for num in sorted(unique_citations):
            info = unique_citations[num]
            lines.append(f"<a id=\"src-{info['num']}\"></a>[{info['num']}] [{info['title']}]({info['url']})")
        
        # Methodology
        total_chunks = sum(len(r.chunks) for r in state.search_results) + len(state.rag_chunks)
        lines.extend([
            "",
            "## Methodology",
            f"- Total chunks retrieved: {total_chunks}",
            f"- Retrieval methods: web search + Qdrant hybrid (vector + keyword + cross-encoder rerank)",
            f"- Quality score: {quality_str} (threshold: {threshold_str})",
            f"- Retry iterations: {state.retry_count}",
            "",
            f"**Sub-queries searched ({len(state.plan.sub_queries) if state.plan else 0}):**",
            ""
        ])
        if state.plan and state.plan.sub_queries:
            for sq in state.plan.sub_queries:
                lines.append(f"- {sq.query} — *{sq.intent}*")
        else:
            lines.append("- No sub-queries recorded.")
        
        # Token usage per LLM-calling agent (planner, synthesizer, critic).
        # writer/searcher/memory_rag don't call an LLM, so they're omitted
        # rather than shown as a misleading 0.
        token_usage = state.token_usage or {}
        if token_usage:
            lines.extend(["", "## Token Usage", ""])
            agent_order = ["planner", "synthesizer", "critic"]
            total_tokens = 0
            for agent_name in agent_order:
                if agent_name in token_usage:
                    tokens = token_usage[agent_name]
                    total_tokens += tokens
                    lines.append(f"- {agent_name.capitalize()}: {tokens:,} tokens")
            # Any other agents not in the expected order (future-proofing)
            for agent_name, tokens in token_usage.items():
                if agent_name not in agent_order:
                    total_tokens += tokens
                    lines.append(f"- {agent_name.capitalize()}: {tokens:,} tokens")
            lines.append(f"- **Total: {total_tokens:,} tokens**")
        
        report = "\n".join(lines)
        
        # Save the citation list for state.citations, so /report can read
        # sources directly instead of re-deriving them separately.
        self.last_citations = [
            {"num": info["num"], "title": info["title"], "url": info["url"]}
            for info in sorted(unique_citations.values(), key=lambda x: x["num"])
        ]
        
        # Store to Qdrant memory
        self._store_to_memory(state, report)
        
        return report
    
    @staticmethod
    def _findings_for_sub_query(sub_query: str, findings: list) -> list:
        """Return findings that answer the given sub-query.

        Tries exact match first (the synthesizer prompt asks the model to
        copy the sub-query text verbatim into Finding.sub_query). Falls
        back to case-insensitive substring matching in either direction,
        in case the model paraphrased slightly instead of copying exactly.
        """
        exact = [f for f in findings if f.sub_query and f.sub_query.strip() == sub_query.strip()]
        if exact:
            return exact
        
        sq_lower = sub_query.strip().lower()
        fuzzy = [
            f for f in findings
            if f.sub_query and (
                f.sub_query.strip().lower() in sq_lower
                or sq_lower in f.sub_query.strip().lower()
            )
        ]
        return fuzzy

    def _format_decline(self, state: AgentState) -> str:
        self.last_citations = []
        chunks_count = sum(len(r.chunks) for r in state.search_results) + len(state.rag_chunks)
        
        return f"""## Insufficient Evidence

InSyfy retrieved {chunks_count} chunks for this query, but none met the minimum evidence threshold.

**Question:** {state.research_question}

**Reason:** {state.decline_reason}

This means the system cannot produce a reliable, grounded answer.

**What to try:**
- Rephrase the question with more specific terms
- Expand the search depth setting
- Try a different topic with more available sources
"""
    
    def _build_citation_map(self, state: AgentState) -> Dict[str, Dict[str, Any]]:
        """Map chunk IDs to citation numbers.

        Citations are deduped by source_url, not chunk_id: several chunks
        commonly come from the same page, and each one should point at the
        same footnote rather than minting a new numbered source every time.
        """
        citations: Dict[str, Dict[str, Any]] = {}   # chunk_id -> citation info
        url_to_citation: Dict[str, Dict[str, Any]] = {}  # source_url -> citation info
        counter = 1

        def _register(chunk):
            nonlocal counter
            url = chunk.metadata.source_url
            title = chunk.metadata.source_title or "Source"

            if url not in url_to_citation:
                url_to_citation[url] = {
                    "num": counter,
                    "title": title,
                    "url": url
                }
                counter += 1

            citations[chunk.chunk_id] = url_to_citation[url]

        for result in state.search_results:
            for chunk in result.chunks:
                _register(chunk)

        for chunk in state.rag_chunks:
            _register(chunk)

        return citations
    
    def _store_to_memory(self, state: AgentState, report: str):
        """Store chunks and report summary to Qdrant."""
        try:
            # Store all chunks
            all_chunks = []
            for result in state.search_results:
                all_chunks.extend(result.chunks)
            all_chunks.extend(state.rag_chunks)
            
            if all_chunks:
                texts = [c.text for c in all_chunks]
                embeddings = self.embedder.encode(texts).tolist()
                qdrant_store.store_chunks(all_chunks, embeddings, state.run_id)
            
            # Store report executive summary
            summary = ""
            if "## Executive Summary" in report:
                try:
                    summary = report.split("## Executive Summary")[1].split("##")[0].strip()
                except:
                    summary = report[:500]
            else:
                summary = report[:500]
            
            summary_embedding = self.embedder.encode([summary]).tolist()[0]
            
            from qdrant_client.models import PointStruct
            report_point_id = str(uuid.uuid5(uuid.NAMESPACE_DNS, f"report_{state.run_id}"))
            qdrant_store.client.upsert(
                collection_name=qdrant_store.collection_name,
                points=[PointStruct(
                    id=report_point_id,
                    vector=summary_embedding,
                    payload={
                        "text": summary,
                        "question": state.research_question,
                        "run_id": state.run_id,
                        "quality_score": state.critique.quality_score if state.critique else 0.0,
                        "type": "report_summary"
                    }
                )]
            )
            
        except Exception as e:
            print(f"Memory storage warning: {e}")